services:  
 prometheus:
   image: prom/prometheus:latest
   ports:
     - 9090:9090
   volumes:
     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
 grafana:
   image: grafana/grafana
   depends_on:
     - prometheus
   ports:
     - 3000:3000
   volumes:
     - ./grafana:/var/lib/grafana
     - ./grafana/provisioning/:/etc/grafana/provisioning/
   restart: unless-stopped
 app:
   build: ./my_flask_app/.
   ports:
     - 5000:5000
   volumes:
     - "./my_flask_app/app.py:/app.py"
