global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'node'
    static_configs:
    - targets:
       - app:5000
  - job_name: prometheus
    static_configs:
    - targets:
       - localhost:9090
